---
- name: deploy_facts.yml
  hosts: all
  become: yes
  become_method: sudo

  vars:
    custom_facts:
      - apache.fact
      - rhn_sub.fact
      - rpm_last.fact

  tasks:
    - name: Create ansible directory
      file:
        path: /etc/ansible
        owner: root
        group: root
        mode: 0755
        state: directory

    - name: Create facts.d directory
      file:
        path: /etc/ansible/facts.d
        owner: root
        group: root
        mode: 0755
        state: directory

    - name: Deploy all facts
      copy:
        src: "files/{{ item }}"
        dest: "/etc/ansible/facts.d/{{ item }}"
        owner: root
        group: root
        mode: 0755
      with_items:
        - "{{ custom_facts }}"