---
- name: deploy_facts.yml
  hosts: all
  become: yes
  become_method: sudo

  vars:
    custom_facts:
      - apache_installed.fact
      - rhn_sub.fact 
      - rpm_last_installed.fact 

tasks:
  - name: Create ansible directory
    file:
      path: /etc/ansible
      uid: root
      gid: root
      mode: 0755

  - name: Create facts.d directory
    file:
      path: /etc/ansible/facts.d
      uid: root
      gid: root
      mode: 0755

  - name: Deploy all facts
    copy:
      src: "{{ item }}"
      uid: root
      gid: root
      mode: 0755
    with_items:
      - custom_facts

    