---

- name: Create ansible root directory
  file:
    path: "{{ ansible_root_dir }}"
    mode: 0755
    state: directory

- name: Clear out existing custom fact files
  file:
    path: "{{ ansible_facts_dir }}"
    state: absent

- name: Create ansible custom facts scripts directory
  file:
    path: "{{ ansible_facts_dir }}"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Put in place custom ansible facts scripts for all OS distributions
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_facts_dir }}"
    owner: root
    group: root
    mode: 0750
  with_fileglob:
    - "{{ ansible_facts_file_pattern }}"

- name: Put in place custom ansible facts scripts for RHEL distributions
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_facts_dir }}"
    owner: root
    group: root
    mode: 0750
  with_fileglob:
    - "{{ ansible_facts_rhel_file_pattern }}"
  when: ansible_distribution == "RedHat"
